[role="pagenumrestart"]
[[intro_what_is_the_lightning_network]]
== Введение

Добро пожаловать в _Освоение Lightning Network_!
(((Welcome to _Mastering the Lightning Network_!)))


((("Lightning Network (generally)", seealso="innovations in Lightning", id="ix_01_introduction-asciidoc0", range="startofrange")))Lightning Network (обычно именующаяся как LN), меняет способ обмена ценностями в Интернете, и это одно из самых захватывающих достижений в истории Биткойна.
Сегодня, в 2021 году, сеть Lightning Network все еще находится в зачаточном состоянии. Lightning Network — это протокол для использования Bitcoin разумным и неочевидным путем. Это технология второго уровня поверх Bitcoin.
(((The Lightning Network (often abbreviated as LN), is changing the way people exchange value online, and it's one of the most exciting advancements to happen in Bitcoin's history.
Today, in 2021, the Lightning Network is still in its infancy. The Lightning Network is a protocol for using Bitcoin in a smart and nonobvious way. It is a second layer technology on top of Bitcoin.)))

Концепция Lightning Network была предложена в 2015, а первая реализация была запущена в 2018. По состоянию на 2021 год мы только начинаем видеть возможности, которые Lightning Network предоставляет Биткойну, включая улучшенную конфиденциальность, скорость и масштабирование.
Обладая базовыми знаниями о Lightning Network, вы можете помочь сформировать будущее сети, а также создать возможности для себя.
(((The concept of the Lightning Network was proposed in 2015, and the first implementation was launched in 2018. As of 2021, we're only beginning to see the opportunities the Lightning Network provides to Bitcoin, including improved privacy, speed, and scale.
With core knowledge of the Lightning Network, you can help shape the future of the network while also building opportunities for yourself.)))

Мы предполагаем, что вы уже обладаете некоторыми базовыми знаниями о Биткойне, но если это не так, не волнуйтесь - мы объясним наиболее важные концепции Биткойна, которые вы должны знать, чтобы понимать работу Lightning Network, в <<bitcoin_fundamentals_review>>. Если вы хотите узнать больше о Биткойне, вы можете прочитать _Освоение Bitcoin_, 2-е издание,  Андреас М. Антонопулос (O'Reilly), которая доступна https://github.com/bitcoinbook/bitcoinbook[бесплатно онлайн].
(((We assume you already have some basic knowledge about Bitcoin, but if not, don't worry—we will explain the most important Bitcoin concepts, those you must know to understand the Lightning Network, in <<bitcoin_fundamentals_review>>. If you want to learn more about Bitcoin, you can read _Mastering Bitcoin_, 2nd edition, by Andreas M. Antonopoulos (O'Reilly), available https://github.com/bitcoinbook/bitcoinbook[for free online].)))

Хотя основная часть этой книги написана для программистов, первые несколько глав написаны так, чтобы быть доступными для любого человека, независимо от его технического уровня. В этой главе мы начнем с терминологии, затем перейдем к рассмотрению доверия и его применения в этих системах, и, наконец, обсудим историю и будущее Lightning Network. Итак начинаем.
(((While the bulk of this book is written for programmers, the first few chapters are written to be approachable by anyone regardless of technical experience. In this chapter, we'll start with some terminology, then move to look at trust and its application in these systems, and finally we'll discuss the history and future of the Lightning Network. Let's get started.)))


=== Основные Концепты Lightning Network
(((Lightning Network Basic Concepts)))

((("Lightning Network (generally)","basic concepts", id="ix_01_introduction-asciidoc1", range="startofrange")))Изучая принцип работы сети Lightning Network, мы столкнемся с технической терминологией, которая поначалу может вызвать некоторое недоумение. Хотя все эти понятия и термины будут подробно объясняться по ходу работы над книгой и определяться в глоссарии, некоторые базовые определения, данные сейчас, облегчат понимание концепций в следующих двух главах. Если вы пока не понимаете всех слов из этих определений, это не страшно. Вы поймете больше по мере продвижения по тексту.
(((As we explore how the Lightning Network actually works, we will encounter some technical terminology that might, at first, be a bit confusing. While all of these concepts and terms will be explained in detail as we progress through the book and are defined in the glossary, some basic definitions now will make it easier to understand the concepts in the next two chapters. If you don't understand all of the words in these definitions yet, that's OK. You'll understand more as you move through the text.)))

Блокчейн (Blockchain):: ((("blockchain","defined")))Распределенный журнал транзакций, создаваемый сетью компьютеров. Например, Bitcoin - это система, которая создает блокчейн. Сеть Lightning Network сама по себе не является блокчейном и не производит блокчейн. Это сеть, которая в опирается на существующий блокчейн для собственной безопасности.
(((Blockchain: A distributed transaction ledger, produced by a network of computers. Bitcoin, for example, is a system that produces a blockchain. The Lightning Network is not itself a blockchain, nor does it produce a blockchain. It is a network that relies on an existing external blockchain for its security.)))

Цифровая подпись (Digital signature):: ((("digital signatures")))Цифровая подпись - это математическая схема для проверки подлинности цифровых сообщений или документов. Валидная цифровая подпись дает получателю основания доверять, что сообщение было создано известным отправителем, что отправитель не может отрицать отправку сообщения и что сообщение не было изменено при передаче.
(((Digital signature: A digital signature is a mathematical scheme for verifying the authenticity of digital messages or documents. A valid digital signature gives a recipient reason to believe that the message was created by a known sender, that the sender cannot deny having sent the message, and that the message was not altered in transit.)))

Хэш функция (Hash Function):: ((("hash function, defined")))Криптографическая хеш-функция это математический алгоритм, который преобразует данные произвольного размера в битовую строку фиксированного размера (хеш) и спроектирован как однонаправленная функция, то есть функция, которую невозможно инвертировать (вычислить обратным способом).
(((Hash function: A cryptographic hash function is a mathematical algorithm that maps data of arbitrary size to a bit string of a fixed size (a hash) and is designed to be a one-way function, that is, a function which is infeasible to invert.)))

Узел (Node):: ((("node, defined")))Компьютер, который участвует в сети. Узел Lightning - это компьютер, который участвует в сети Lightning Network. Узел Bitcoin - это компьютер, который участвует в сети Bitcoin. Обычно пользователь LN запускает узел Lightning _и_ узел Bitcoin.
(((Node: A computer that participates in a network. A Lightning node is a computer that participates in the Lightning Network. A Bitcoin node is a computer that participates in the Bitcoin network. Typically an LN user will run a Lightning node _and_ a Bitcoin node.)))

On-chain против off-chain:: ((("on-chain payment","defined")))Платеж считается _on-chain_ (в цепи), если он записан как транзакция в блокчейне Bitcoin (или другого основного) блокчейна. ((("off-chain payment")))Платежи, отправленные через платежные каналы между узлами Lightning и которые не отображаются в основном блокчейне, называются _off-chain_ платежи (вне цепи). Обычно в Lightning Network единственные on-chain транзакции - это те, которые используются для открытия и закрытия платежного канала Lightning. Сущестсвует третий тип каналов модифицирующий транзакцию, именуемый сращивание (splicing) который может быть использован для добавления/удаления всех средств зафиксированных в канале.
(((On-chain versus off-chain: A payment is _on-chain_ if it is recorded as a transaction on the Bitcoin (or other underlying) blockchain. Payments sent via payment channels between Lightning nodes, and which are not visible in the underlying blockchain, are called _off-chain_ payments. Usually in the Lightning Network, the only on-chain transactions are those used to open and close a Lightning payment channel. A third type of channel modifying transaction exists, called splicing, which can be used to add/remove the amount of funds committed in a channel.)))

Оплата (Payment):: ((("payment","defined")))Когда обмен ценностями происходит в Lightning Network, мы называем это "оплатой", а не "транзакцией" как в блокчейне Bitcoin.
(((Payment: When value is exchanged on the Lightning Network, we call this a "payment" as compared to a "transaction" on the Bitcoin blockchain.)))

Канал оплаты (Payment channel):: ((("payment channel", seealso="channel entries")))_Финансовые отношения_ между двумя узлами сети Lightning Network, обычно реализуемые с помощью мульти подписанных Bitcoin транзакций, которые передают контроль над биткоином между двумя узлами Lightning.
(((Payment channel: A _financial relationship_ between two nodes on the Lightning Network, typically implemented by multisignature Bitcoin transactions that share control over bitcoin between the two Lightning nodes.)))

Маршрутизация против отправки (Routing vs Sending):: ((("routing","sending versus")))((("sending, routing versus")))В отличие от Биткойна, где транзакции «отправляются» путем трансляции их всем, Lightning это маршрутизируемая сеть, в которой платежи «маршрутизируются» через один или несколько платежных каналам, следуя _пути_ от отправителя к получателю.

Транзакция (Transaction):: ((("transaction, defined")))Структура данных, которая фиксирует передачу контроля над некоторыми средствами (например, немного биткойнов). Сеть Lightning полагается на транзакции Bitcoin (или транзакций другого блокчейна) для отслеживания контроля над средствами.
(((Transaction: A data structure that records the transfer of control over some funds (e.g., some bitcoin). The Lightning Network relies on Bitcoin transactions (or those of another blockchain) to track control of funds.)))

Более подробные определения этих и многих других терминов можно найти в <<glossary>>. В этой книге мы объясним, что означают эти концепции и как на самом деле работают эти технологии
(((More detailed definitions of these and many other terms can be found in the <<glossary>>. Throughout this book, we will explain what these concepts mean and how these technologies actually work.)))

[TIP]
====
На протяжении всей этой книги вы будете встречать слово «Биткойн» с заглавной буквы, которое относится к «системе Биткойн» и является именем собственным. Вы также увидите слово «биткойн» со строчной буквой _б_, обозначающей денежную единицу. Каждый биткойн подразделяется на 100 миллионов единиц, каждая из которых называется «сатоши»(во множественном и единственном числе), на английском же "satoshi" (единственное) or "satoshis" (множественное).(((range="endofrange", startref="ix_01_introduction-asciidoc1")))
(((Throughout this book, you will see "Bitcoin" with the first letter capitalized, which refers to the _Bitcoin system_ and is a proper noun. You will also see "bitcoin," with a lowercase _b_, which refers to the currency unit. Each bitcoin is further subdivided into 100 million units each called a "satoshi" (singular) or "satoshis" (plural).)))
====

Теперь, когда вы знакомы с этими основными терминами, давайте перейдем к понятию, которое вам уже знакомо: доверие.
(((Now that you're familiar with these basic terms, let's move to a concept you are already comfortable with: trust.)))

=== Доверие в Децентрализованных Сетях
(((Trust in Decentralized Networks)))

((("Lightning Network (generally)","trust in decentralized networks")))((("trustless systems","trust in decentralized networks")))
Часто можно услышать, как люди называют Биткойн и Lightning Network "не требующими доверия". На первый взгляд это вызывает недоумение. В конце концов, хорошая ли вещь отсутствие доверия? Банки даже используют это в своих названиях! Является ли "не требующая доверия" система, система, лишенная доверия - плохой вещью?
(((You will often hear people calling Bitcoin and the Lightning Network "trustless." At first glance this is confusing. After all, isn't trust a good thing? Banks even use it in their names! Isn't a "trustless" system, a system devoid of trust, a bad thing?)))

Использование слова «не требующий доверия» подразумевает передачу возможности действовать без _нужды_ доверять другим участникам системы. В децентрализованной системе, такой как Биткойн, вы всегда можете выбрать кого-то кому вы доверяете чтобы совершить сделку. Однако система гарантирует, что вас невозможно обмануть, даже если вы не можете доверять другой стороне транзакции. Доверие — это желательное, а не обязательное свойство системы.
(((The use of the word "trustless" is intended to convey the ability to operate without _needing_ trust in the other participants in the system. In a decentralized system like Bitcoin, you can always choose to transact with someone you trust. However, the system ensures you can't be cheated even if you can't trust the other party in a transaction. Trust is a nice-to-have instead of a must-have property of the system.)))

В сравнении с традиционными системами, такими как банки, где вы обязаны доверять третьей стороне, поскольку она контролирует ваши деньги. Если банк злоупотребляет вашим доверием, вы, возможно сможете обратиться за помощью к регулирующему органу или суду, но это потребует огромных затрат времени, денег и сил.
(((Contrast that to traditional systems like banking where you must place your trust in a third party, since it controls your money. If the bank violates your trust, you may be able to find some recourse from a regulator or court, but at an enormous cost of time, money, and effort.)))

Не требует доверия не означает лишенное доверия. Это означает, что доверие не является обязательным условием для всех транзакций и то что вы можете совершать транзакции даже с людьми, которым не доверяете, поскольку система препятствует обману.
(((Trustless does not mean devoid of trust. It means that trust is not a necessary prerequisite to all transactions and that you can transact even with people you don't trust because the system prevents cheating.)))

Прежде чем перейти к рассмотрению принципов работы Lightning Network, важно понять одну базовую концепцию, лежащую в основе Bitcoin, Lightning Network и многих других подобных систем: мы называем это _протоколом справедливости_ (fairness protocol). Протокол справедливости - это способ достижения справедливых результатов между участниками, которые не обязаны доверять друг другу, без участия центрального органа, и это основа децентрализованных систем, таких как Bitcoin.
(((Before we get into how the Lightning Network works, it's important to understand one basic concept that underlies Bitcoin, the Lightning Network, and many other such systems: something we call a _fairness protocol_. A fairness protocol is a way to achieve fair outcomes between participants, who do not need to trust each other, without the need for a central authority, and it is the backbone of decentralized systems like Bitcoin.)))


=== Справедливость Без Центрального Управления
(((Fairness Without Central Authority)))

((("fairness, ensuring")))((("Lightning Network (generally)","fairness without central authority")))Когда у людей есть конкурирующие интересы, как они могут установить достаточное доверие, чтобы участвовать в каком-либо сотрудничестве или транзакционном поведении? Ответ на этот вопрос лежит в основе нескольких научных и гуманитарных дисциплин, таких как экономика, социология, поведенческая психология и математика. Некоторые из этих дисциплин дают нам «мягкие-социальные» ответы, которые зависят от таких понятий, как репутация, справедливость, мораль и даже религия. Другие дисциплины дают нам конкретные ответы, которые зависят только от предположения, что участники этих взаимодействий будут действовать рационально, руководствуясь своими личными интересами в качестве главной цели.(((When people have competing interests, how can they establish enough trust to engage in some cooperative or transactional behavior? The answer to this question lies at the core of several scientific and humanistic disciplines, such as economics, sociology, behavioral psychology, and mathematics. Some of those disciplines give us "soft" answers that depend on concepts such as reputation, fairness, morality, and even religion. Other disciplines give us concrete answers that depend only on the assumption that the participants in these interactions will act rationally, with their self-interest as the main objective.)))

В общих чертах существует несколько способов обеспечить справедливые результаты во взаимодействии между людьми, которые могут иметь конкурирующие интересы:
(((In broad terms, there are a handful of ways to ensure fair outcomes in interactions between individuals who may have competing interests:)))

Требование доверия:: Вы взаимодействуете только с людьми, которым уже доверяете благодаря предыдущим взаимодействиям, репутации или семейным отношениям. Это работает достаточно хорошо в небольших масштабах, особенно в семьях и небольших группах, что является наиболее распространенной основой для коллективного поведения. К сожалению, этот способ не масштабируется и страдает от трайбалистской (внутригрупповой) предвзятости.
(((Require trust: You only interact with people whom you already trust, due to prior interactions, reputation, or familial relationships. This works well enough at small scale, especially within families and small groups, that it is the most common basis for cooperative behavior. Unfortunately, it doesn't scale and it suffers from tribalist (in-group) bias.)))

Верховенство закона:: Установите правила взаимодействия, соблюдение которых обеспечивается институтом(группой управляющих). Этот способ лучше масштабируется, но не может масштабироваться в глобальном масштабе из-за различий в обычаях и традициях, а также неспособности масштабировать институты исполнительной власти. Одним из неприятных побочных эффектов этого решения является то, что институты становятся все более и более могущественными по мере их роста, и это может привести к коррупции.
(((Rule of law: Establish rules for interactions that are enforced by an institution. This scales better, but it cannot scale globally due to differences in customs and traditions, as well as the inability to scale the institutions of enforcement. One nasty side effect of this solution is that the institutions become more and more powerful as they get bigger and that may lead to corruption.)))

Доверенные третьи стороны (third parties):: В каждое взаимодействие вводится посредник для обеспечения справедливости. В сочетании с "верховенством закона" чтобы обеспечить надзор за посредниками, этот вариант лучше масштабируется, но страдает от того же дисбаланса власти: посредники становятся очень влиятельными и могут привлекать коррупцию. Концентрация власти приводит к системным рискам и системным сбоям ("слишком большой, чтобы обанкротиться").
(((Trusted third parties: Put an intermediary in every interaction to enforce fairness. Combined with the "rule of law" to provide oversight of intermediaries, this scales better, but suffers from the same imbalance of power: the intermediaries get very powerful and may attract corruption. Concentration of power leads to systemic risk and systemic failure ("too big to fail").)))

Теоретико-игровые протоколы честности (справедливости):: Эта последняя категория возникает из сочетания Интернета и криптографии и является предметом данного раздела. Давайте посмотрим, как работает этот способ и в чем его преимущества и недостатки.
(((Game theoretical fairness protocols: This last category emerges from the combination of the internet and cryptography and is the subject of this section. Let's see how it works and what its advantages and disadvantages are.)))

==== Доверенные Протоколы Без Посредников
(((Trusted Protocols Without Intermediaries)))

((("fairness protocol","trusted protocols without intermediaries")))Криптографические системы, такие как Bitcoin и Lightning Network, — это системы, которые позволяют вам совершать транзакции с людьми (и компьютерами), которым вы не доверяете. Эту операцию часто называют «не требующей доверия» операцией, хотя на самом деле она не является таковой. Вы должны доверять программному обеспечению, которое используете, и доверять что протокол, реализованный этим программным обеспечением, приведет к справедливым результатам.
(((Cryptographic systems like Bitcoin and the Lightning Network are systems that allow you to transact with people (and computers) that you don't trust. This is often referred to as "trustless" operation, even though it is not actually trustless. You have to trust in the software that you run, and you have to trust that the protocol implemented by that software will result in fair outcomes.)))

Большое различие между такой криптографической системой и традиционной финансовой системой в том, что в традиционных финансах у вас есть _доверенная третья сторона_, например банк, которая гарантирует справедливость результатов. Серьезной проблемой таких систем является то, что они предоставляют слишком много полномочий третьей стороне, а также уязвимы к _единственной точке отказа_. Если доверенная третья сторона сама нарушает доверие или пытается обмануть, разрушается основа доверия.
(((The big distinction between a cryptographic system like this and a traditional financial system is that in traditional finance you have a _trusted third party_, for example a bank, to ensure that outcomes are fair. A significant problem with such systems is that they give too much power to the third party, and they are also vulnerable to a _single point of failure_. If the trusted third party itself violates trust or attempts to cheat, the basis of trust breaks.)))

Изучая криптографические системы, вы заметите определенную закономерность: вместо того, чтобы полагаться на доверенную третью сторону, эти системы пытаются предотвратить несправедливые результаты, используя систему стимулов и сдерживающих факторов. В криптографических системах вы предоставляете доверие ((("protocol, defined")))_протоколу_, который является эффективной системой с набором правил, которая, если спроектирована правильно, будет правильно применять нужные стимулы и сдерживающие факторы. Преимущество этого подхода двоякое: вы не только избегаете доверия третьей стороне, но и уменьшаете необходимость принуждения к справедливым результатам. Пока участники следуют согласованному протоколу и остаются в системе, механизм стимулирования в этом протоколе обеспечивает справедливые результаты без принуждения.
(((As you study cryptographic systems, you will notice a certain pattern: instead of relying on a trusted third party, these systems attempt to prevent unfair outcomes by using a system of incentives and disincentives. In cryptographic systems you place trust in the ("protocol, defined")_protocol_, which is effectively a system with a set of rules that, if properly designed, will correctly apply the desired incentives and disincentives. The advantage of this approach is twofold: not only do you avoid trusting a third party, you also reduce the need to enforce fair outcomes. So long as the participants follow the agreed protocol and stay within the system, the incentive mechanism in that protocol achieves fair outcomes without enforcement.)))

((("game theory")))Использование стимулов и ограничений для достижения справедливых результатов является одним из аспектов раздела математики, называемого _теорией игр_, который изучает "модели стратегического взаимодействия между рационально мыслящими людьми". "footnote:[The Wikipedia https://en.wikipedia.org/wiki/Game_theory[entry on game theory] provides more information.] Криптографические системы, которые контролируют финансовые взаимодействия между участниками, такие как Bitcoin и Lightning Network, в значительной степени полагаются на теорию игр, чтобы препятствовать мошенничеству участников и позволить участникам, которые не доверяют друг другу достигать справедливых результатов.
(((The use of incentives and disincentives to achieve fair outcomes is one aspect of a branch of mathematics called _game theory_, which studies "models of strategic interaction among rational decision makers."footnote:[The Wikipedia https://en.wikipedia.org/wiki/Game_theory[entry on game theory] provides more information.] Cryptographic systems that control financial interactions between participants, such as Bitcoin and the Lightning Network, rely heavily on game theory to prevent participants from cheating and allow participants who don't trust each other to achieve fair outcomes.)))

Хотя теория игр и ее использование в криптографических системах на первый взгляд могут показаться запутанными и незнакомыми, есть вероятность, что вы уже знакомы с этими системами в своей повседневной жизни; вы просто их еще не распознаете. В следующем разделе мы воспользуемся простым примером из детства, который поможет нам определить основную закономерность. Как только вы поймете базовый шаблон, вы увидите его повсюду в пространстве блокчейна и начнете распознавать его быстро и интуитивно.
(((While game theory and its use in cryptographic systems may appear confounding and unfamiliar at first, chances are you're already familiar with these systems in your everyday life; you just don't recognize them yet. In the following section we'll use a simple example from childhood to help us identify the basic pattern. Once you understand the basic pattern, you will see it everywhere in the blockchain space and you will come to recognize it quickly and intuitively.)))

((("fairness protocol", id="ix_01_introduction-asciidoc2", range="startofrange")))В этой книге мы называем эту модель((("fairness protocol","defined"))) _протоколом справедливости_, определяемым как процесс, который использует систему стимулов и/или сдерживающих факторов для обеспечения справедливых результатов для участников, которые не доверяют друг другу. Принуждение соблюдения протокола справедливости необходимо только для того, чтобы гарантировать, что участники не смогут избежать стимулов или сдерживающих факторов.
(((In this book, we call this pattern a ("fairness protocol","defined")_fairness protocol_, defined as a process that uses a system of incentives and/or disincentives to ensure fair outcomes for participants who don't trust each other. Enforcement of a fairness protocol is only necessary to ensure that the participants can't escape the incentives or disincentives.)))

==== Протокол Справедливости в Действии
(((A Fairness Protocol in Action)))

((("fairness protocol","real-world example")))Давайте рассмотрим пример протокола справедливости, с которым вы, возможно, уже знакомы.
(((Let's look at an example of a fairness protocol that you may already be familiar with.)))

Представьте себе семейный перекус с родителем и двумя детьми. Дети привередливы в еде, и единственное, что они согласятся съесть — это картошку фри. Родитель купил в ближайшем фастфуде упаковку картофеля фри. Двое детей должны разделить упаковку между собой. Родитель должен обеспечить справедливое распределение картошки каждому ребенку; в противном случае родителю придется слышать постоянные жалобы (возможно, весь день), и всегда существует вероятность того, что несправедливая ситуация перерастет в насилие. Что делать родителю?
(((использую вольный перевод упаковка не тарелка)))
(((Imagine a family lunch, with a parent and two children. The children are fussy eaters and the only thing they will agree to eat is fried potatoes. The parent has prepared a bowl of fried potatoes ("french fries" or "chips" depending on which English dialect you use). The two siblings must share the plate of chips. The parent must ensure a fair distribution of chips to each child; otherwise, the parent will have to hear constant complaining (maybe all day), and there's always a possibility of an unfair situation escalating to violence. What is a parent to do?)))

Есть несколько разных способов достижения справедливости в этом стратегическом взаимодействии между детьми, которые не доверяют друг другу и имеют конкурирующие интересы. Наивный, но широко используемый метод заключается в том, что родитель использует свой авторитет как доверенное третье лицо: они разделяеют упаковку картошки на две порции. Это похоже на традиционные финансы, где банк, бухгалтер или юрист действуют как доверенная третья сторона, препятствующая любому мошенничеству между двумя сторонами, желающими совершить сделку.
(((There are a few different ways that fairness can be achieved in this strategic interaction between two siblings that do not trust each other and have competing interests. The naive but commonly used method is for the parent to use their authority as a trusted third party: they split the bowl of chips into two servings. This is similar to traditional finance, where a bank, accountant, or lawyer acts as a trusted third party to prevent any cheating between two parties who want to transact.)))

Проблема этой ситуации в том, что он передает большую власть и ответственность в руки доверенной третьей стороны. В этом примере родитель несет полную ответственность за равное распределение картошки, а стороны просто ждут, наблюдают и жалуются. Дети обвиняют родителя в том, что он выбирает любимчика и несправедливо распределяет картошку. Дети дерутся из-за кусочка который больше, кричат: «Эта больше!» и втягивают родителя в их ссору. Звучит ужасно, не так ли? Должен ли родитель кричать громче? Забрать картошку у обоих и убрать? Пригрозить никогда больше не покупать картошку фри и оставить этих неблагодарных детей голодными?
(((The problem with this scenario is that it vests a lot of power and responsibility in the hands of the trusted third party. In this example, the parent is fully responsible for the equal allocation of chips, and the parties merely wait, watch, and complain.  The children accuse the parent of playing favorites and not allocating the chips fairly. The siblings fight over the chips, yelling "that chip is bigger!" and dragging the parent into their fight. It sounds awful, doesn't it? Should the parent yell louder? Take all of the chips away? Threaten to never make chips again and let those ungrateful children go hungry?)))

Существует гораздо лучшее решение: научим детей играть в игру под названием «раздели и выбери». За каждым обедом один из детей делит упаковку картошки фри на две порции, а _другой_ ребенок может выбрать, какую порцию он хочет. Почти сразу братья и сестры понимают динамику этой игры. Если разделяющий совершит ошибку или попытается схитрить, другой может "наказать" его, выбрав порцию большего размера. Играть честно — в интересах обоих детей, но особенно того, кто разделяет. В этом случае проигрывает только мошенник. Родителю даже не нужно использовать свой авторитет или обеспечивать справедливость. Все, что нужно сделать родителю, это обеспечить/принудить к _соблюдению протокола_; до тех пор, пока дети не смогут выйти из отведенной им роли «разделителя» и «выборщика», сам протокол обеспечивает справедливый результат без необходимости какого-либо вмешательства. Родитель не может выбирать любимчиков или искажать результат.
(((A much better solution exists: the siblings are taught to play a game called "split and choose." At each lunch one sibling splits the bowl of chips into two servings and the _other_ sibling gets to choose which serving they want. Almost immediately, the siblings figure out the dynamic of this game. If the one splitting makes a mistake or tries to cheat, the other sibling can "punish" them by choosing the bigger bowl. It is in the best interest of both siblings, but especially the one splitting the bowl, to play fair. Only the cheater loses in this scenario. The parent doesn't even have to use their authority or enforce fairness. All the parent has to do is _enforce the protocol_; as long as the siblings cannot escape their assigned roles of "splitter" and "chooser," the protocol itself ensures a fair outcome without the need for any intervention. The parent can't play favorites or distort the outcome.)))

[WARNING]
====
Хотя печально известные битвы за картошку 1980-х годов прекрасно иллюстрируют смысл, любое сходство между предыдущей ситуацией и каким-либо реальным детским опытом авторов книги с их братьями/сестрами является полностью случайным... или нет?
(((While the infamous chip battles of the 1980s neatly illustrate the point, any similarity between the preceding scenario and any of the authors' actual childhood experiences with their cousins is entirely coincidental...or is it?)))
====

==== Примитивы Безопасности как Строительные Блоки
(((Security Primitives as Building Blocks)))

((("fairness protocol","security primitives as building blocks")))((("security primitives")))
Чтобы протокол справедливости, подобный этому, работал, необходимы определенные гарантии или _примитивы безопасности_, которые можно комбинировать для обеспечения исполнения протокола. Первый примитив безопасности — это _строгий временной порядок/последовательность_: действие "разделения" должно произойти до действия "выбора". Это не сразу очевидно, но если вы не можете гарантировать, что действие А произойдет раньше действия Б, протокол развалится(будет иметь уязвимость). Второй примитив безопасности — это "обязательство без возможности отказа". Каждый ребенок должен выбрать свою роль: либо разделитель, либо выборщик. Кроме того, как только разделение завершено, разделитель сохраняет свое решение о разделении — он не может отказаться от этого выбора и попытаться еще раз.
(((In order for a fairness protocol like this to work, there need to be certain guarantees, or _security primitives_, that can be combined to ensure enforcement. The first security primitive is _strict time ordering/sequencing_: the "splitting" action must happen before the "choosing" action. It's not immediately obvious, but unless you can guarantee that action A happens before action B, then the protocol falls apart. The second security primitive is _commitment with nonrepudiation_. Each sibling must commit to their choice of role: either splitter or chooser. Also, once the splitting has been completed, the splitter is committed to the split they created—they cannot repudiate that choice and go try again.)))

Криптографические системы предлагают ряд примитивов безопасности, которые можно комбинировать различными способами для создания протокола справедливости. Помимо *_последовательности действий_* и *_неотказных обязательств_*, мы также можем использовать множество других инструментов:
(((Cryptographic systems offer a number of security primitives that can be combined in different ways to construct a fairness protocol. In addition to sequencing and commitment, we can also use many other tools:)))

- Хэш-функции для подписи данных в качестве формы обязательства или в качестве основы для цифровой подписи.
(((- Hash functions to fingerprint data, as a form of commitment, or as the basis for a digital signature)))
- Цифровые подписи для аутентификации, неотказных обязательств и доказательства владения секретом.
(((- Digital signatures for authentication, nonrepudiation, and proof of ownership of a secret)))
- Шифрование/дешифрование для предоставления доступа к информации *_только авторизованным_* участникам.
(((- Encryption/decryption to restrict access to information to authorized participants only)))

Это лишь небольшой список из целого «зоопарка» защитных и криптографических примитивов, которые используются. Постоянно изобретаются более интересные(((базовые))) примитивы и комбинации взаимодействия.
(((This is only a small list of a whole "menagerie" of security and cryptographic primitives that are in use. More basic primitives and combinations are invented all the time.)))

В нашем примере из реальной жизни мы видели одну из форм протокола справедливости, называемую «раздели и выбери». Это лишь один из множества различных протоколов справедливости, которые можно создать, комбинируя различными способами строительные блоки примитивов безопасности. Но основная схема всегда одна и та же: два или более участников взаимодействуют, не доверяя друг другу, выполняя ряд шагов, которые являются частью согласованного протокола. Шаги протокола предусматривают стимулы и наказания, гарантирующие, что, если участники рациональны, мошенничество будет контрпродуктивным, а справедливость станет автоматическим результатом. Принужение не требуется для достижения справедливых результатов — оно необходимо лишь для удержания участников от нарушения согласованного протокола.
(((In our real-life example, we saw one form of fairness protocol called "split and choose." This is just one of a myriad different fairness protocols that can be built by combining the building blocks of security primitives in different ways. But the basic pattern is always the same: two or more participants interact without trusting each other by engaging in a series of steps that are part of an agreed protocol. The protocol's steps arrange incentives and disincentives to ensure that if the participants are rational, cheating is counterproductive and fairness is the automatic outcome. Enforcement is not necessary to get fair outcomes—it is only necessary to keep the participants from breaking out of the agreed protocol.)))

Теперь, когда вы понимаете эту базовую закономерность, вы начнете видеть ее повсюду в Bitcoin, Lightning Network и во многих других системах. Далее рассмотрим некоторые конкретные примеры.
(((Now that you understand this basic pattern, you will start seeing it everywhere in Bitcoin, the Lightning Network, and many other systems. Let's look at some specific examples next.)))

==== Example of the Fairness Protocol

((("fairness protocol","Proof of Work example")))((("PoW (Proof of Work) algorithm")))((("Proof of Work (PoW) algorithm")))The most prominent example of a fairness protocol is Bitcoin's consensus algorithm, Proof of Work (PoW). In Bitcoin, miners compete to verify transactions and aggregate them in blocks. To ensure that the miners do not cheat, without entrusting them with authority, Bitcoin uses a system of incentives and disincentives. Miners have to use electricity and dedicate hardware doing "work" that is embedded as a "proof" inside every block. This is achieved because of a property of hash functions where the output value is randomly distributed across the entire range of possible outputs. If miners succeed in producing a valid block fast enough, they are rewarded by earning the block reward for that block. Forcing miners to use a lot of electricity before the network considers their block means that they have an incentive to correctly validate the transactions in the block. If they cheat or make any kind of mistake, their block is rejected and the electricity they used to "prove" it is wasted. No one needs to force miners to produce valid blocks; the reward and punishment incentivize them to do so. All the protocol needs to do is ensure that only valid blocks with Proof of Work are accepted.

The fairness protocol pattern can also be found in many different aspects of the Lightning Network:

* Those who fund channels make sure that they have a refund transaction signed before they publish the funding transaction.

* Whenever a channel is moved to a new state, the old state is "revoked" by ensuring that if anyone tries to broadcast it, they lose the entire balance and get punished.

* Those who forward payments know that if they commit funds forward, they can either get a refund or get paid by the node preceding them.

Again and again, we see this pattern. Fair outcomes are not enforced by any authority. They emerge as the natural consequence of a protocol that rewards fairness and punishes cheating, a fairness protocol that harnesses self-interest by directing it toward fair outcomes.

Bitcoin and the Lightning Network are both implementations of fairness protocols. So why do we need the Lightning Network? Isn't Bitcoin enough?(((range="endofrange", startref="ix_01_introduction-asciidoc2")))


=== Motivation for the Lightning Network

((("Lightning Network (generally)","motivation for", id="ix_01_introduction-asciidoc3", range="startofrange")))Bitcoin is a system that records transactions on a globally replicated public ledger. Every transaction is seen, validated, and stored by every participating computer. As you can imagine, this generates a lot of data and is difficult to scale.

As Bitcoin and the demand for transactions grew, the number of transactions in each block increased until it eventually reached the block size limit.
Once blocks are "full," excess transactions are left to wait in a queue. Many users will increase the fees they're willing to pay to buy space for their transactions in the next block.

If demand continues to outpace the capacity of the network, an increasing number of users' transactions are left waiting unconfirmed. Competition for fees also increases the cost of each transaction, making many smaller-value transactions (e.g., microtransactions) completely uneconomical during periods of particularly high demand.

To solve this problem, we could increase the block size limit to create space for more transactions. An increase in the "supply" of block space will lead to a lower price equilibrium for transaction fees.

However, increasing block size shifts the cost to node operators and requires them to expend more resources to validate and store the blockchain. Because blockchains are gossip protocols, each node is required to know and validate every single transaction that occurs on the network. Furthermore, once validated, each transaction and block must be propagated to the node's "neighbors," multiplying the bandwidth requirements. As such, the greater the block size, the greater the bandwidth, processing, and storage requirements for each individual node. Increasing transaction capacity in this way has the undesirable effect of centralizing the system by reducing the number of nodes and node operators. Since node operators are not compensated for running nodes, if nodes are very expensive to run, only a few well-funded node operators will continue to run nodes.

==== Scaling Blockchains

((("blockchain","scaling", id="ix_01_introduction-asciidoc4", range="startofrange")))((("Lightning Network (generally)","scaling blockchains", id="ix_01_introduction-asciidoc5", range="startofrange")))The side effects of increasing the block size or decreasing the block time with respect to centralization of the network are severe, as a few calculations with the numbers show.

Let us assume the usage of Bitcoin grows so that the network has to process 40,000 transactions per second, which is the approximate transaction processing level of the Visa network during peak usage.

Assuming 250 bytes on average per transaction, this would result in a data stream of 10 megabytes per second (MBps) or 80 megabits per second (Mbps) just to be able to receive all the transactions.
This does not include the traffic overhead of forwarding the transaction information to other peers.
While 10 MBps does not seem extreme in the context of high-speed fiber optic and 5G mobile speeds, it would effectively exclude anyone who cannot meet this requirement from running a node, especially in countries where high-performance internet is not affordable or widely available.

Users also have many other demands on their bandwidth and cannot be expected to expend this much only to receive transactions.

Furthermore, storing this information locally would result in 864 gigabytes per day. This is roughly one terabyte of data, or the size of a hard drive.


Verifying 40,000 Elliptic Curve Digital Signature Algorithm (ECDSA) signatures per second is also barely feasible (see https://bitcoin.stackexchange.com/questions/95339/how-many-bitcoin-transactions-can-be-verified-per-second[this article on StackExchange]), making the _initial block download (IBD)_ of the Bitcoin blockchain  (synchronizing and verifying everything starting from the genesis block) almost impossible without very expensive hardware.

While 40,000 transactions per second seems like a lot, it only achieves parity with traditional financial payment networks at peak times. Innovations in machine-to-machine payments, microtransactions, and other applications are likely to push demand to many orders higher than that.

Simply put: you can't scale a blockchain to validate the entire world's transactions in a decentralized way.

_But what if each node wasn't required to know and validate every single transaction? What if there was a way to have scalable off-chain transactions, without losing the security of the Bitcoin network?_

In February 2015, Joseph Poon and Thaddeus Dryja proposed a possible solution to the Bitcoin scalability problem, with the publication of "The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments."footnote:[Joseph Poon and Thaddeus Dryja. "The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments." DRAFT Version 0.5.9.2. January 14, 2016. https://lightning.network/lightning-network-paper.pdf[].]

In the (now outdated) whitepaper, Poon and Dryja estimate that in order for Bitcoin to reach the 47,000 transactions per second processed at peak by Visa, it would require 8 GB blocks.
This would make running a node completely untenable for anyone but large-scale enterprises and industrial-grade operations.
The result would be a network in which only a few users could actually validate the state of the ledger.
Bitcoin relies on users validating the ledger for themselves, without explicitly trusting third parties, in order to stay decentralized.
Pricing users out of running nodes would force the average user to trust third parties to discover the state of the ledger, ultimately breaking the trust model of Bitcoin.

The Lightning Network proposes a new network, a second layer, where users can make payments to each other peer-to-peer, without the necessity of publishing a transaction to the Bitcoin blockchain for each payment.
Users may pay each other on the Lightning Network as many times as they want, without creating additional Bitcoin transactions or incurring on-chain fees.
They only make use of the Bitcoin blockchain to load bitcoin onto the Lightning Network initially and to _settle_, that is, to remove bitcoin from the Lightning Network.
The result is that many more Bitcoin payments can take place off-chain, with only the initial loading and final settlement transactions needing to be validated and stored by Bitcoin nodes.
Aside from reducing the burden on nodes, payments on the Lightning Network are cheaper for users because they do not need to pay blockchain fees, and more private for users because they are not published to all participants of the network and furthermore are not stored permanently.

While the Lightning Network was initially conceived for Bitcoin, it can be implemented on any blockchain that meets some basic technical requirements. Other blockchains, such as Litecoin, already support the Lightning Network. Additionally, several other blockchains are developing similar second layer or "layer 2" solutions to help them scale(((range="endofrange", startref="ix_01_introduction-asciidoc5")))(((range="endofrange", startref="ix_01_introduction-asciidoc4"))).(((range="endofrange", startref="ix_01_introduction-asciidoc3")))

=== The Lightning Network's Defining Features

((("Lightning Network (generally)","defining features")))The Lightning Network is a network that operates as a second layer protocol on top of Bitcoin and other blockchains. The Lightning Network enables fast, secure, private, trustless, and permissionless payments. Here are some of the features of the Lightning Network:

 * Users of the Lightning Network can route payments to each other for low cost and in real time.
 * Users who exchange value over the Lightning Network do not need to wait for block confirmations for payments.
 * Once a payment on the Lightning Network has completed, usually within a few seconds, it is final and cannot be reversed. Like a Bitcoin transaction, a payment on the Lightning Network can only be refunded by the recipient.
 * Whereas on-chain Bitcoin transactions are broadcast and verified by all nodes in the network, payments routed on the Lightning Network are transmitted between pairs of nodes and are not visible to everyone, resulting in much greater privacy.
 * Unlike transactions on the Bitcoin network, payments routed on the Lightning Network do not need to be stored permanently. Lightning thus uses fewer resources and hence is cheaper. This property also has benefits for privacy.
 * The Lightning Network uses onion routing, similar to the protocol used by The Onion Router (Tor) privacy network, so that even the nodes involved in routing a payment are only directly aware of their predecessor and successor in the payment route.
 * When used on top of Bitcoin, the Lightning Network uses real bitcoin, which is always in the possession (custody) and full control of the user. Lightning is not a separate token or coin, it _is_ Bitcoin.


[[user-stories]]
=== Lightning Network Use Cases, Users, and Their Stories

((("Lightning Network (generally)","use cases and users")))To better understand how the Lightning Network actually works, and why people use it, we'll be following a number of users and their stories.

In our examples, some of the people have already used Bitcoin and others are completely new to the Bitcoin network. Each person and their story, as listed here, illustrate one or more specific use cases. We'll be revisiting them throughout this book:

Consumer::
Alice is a Bitcoin user who wants to make fast, secure, cheap, and private payments for small retail purchases. She buys coffee with bitcoin, using the Lightning Network.

Merchant::
Bob owns a coffee shop, "Bob's Cafe." On-chain Bitcoin payments don't scale for small amounts like a cup of coffee, so he uses the Lightning Network to accept Bitcoin payments almost instantaneously and for low fees.

Software service business::
Chan is a Chinese entrepreneur who sells information services related to the Lightning Network, as well as Bitcoin and other cryptocurrencies. Chan is selling these information services over the internet by implementing micropayments over the Lightning Network. Additionally, Chan has implemented a liquidity provider service that rents inbound channel capacity on the Lightning Network, charging a small bitcoin fee for each rental period.

Gamer::
Dina is a teenage gamer from Russia. She plays many different computer games, but her favorite ones are those that have an "in-game economy" based on real money. As she plays games, she also earns money by acquiring and selling virtual in-game items. The Lightning Network allows her to transact in small amounts for in-game items as well as earn small amounts for completing quests.

=== Conclusion

In this chapter, we talked about the fundamental concept that underlies both Bitcoin and the Lightning Network: the fairness protocol.

We looked at the history of the Lightning Network and the motivations behind second layer scaling solutions for Bitcoin and other blockchain-based networks.

We learned basic terminology including node, payment channel, on-chain transactions, and off-chain payments.

Finally, we met Alice, Bob, Chan, and Dina, whom we'll be following throughout the rest of the book.(((range="endofrange", startref="ix_01_introduction-asciidoc0"))) In the next chapter, we'll meet Alice and walk through her thought process as she selects a Lightning wallet and prepares to make her first Lightning payment to buy a cup of coffee from Bob's Cafe.((("Bitcoin (system)","Lightning Network compared to", see="Bitcoin–Lightning Network comparisons")))((("channel", see="payment channel")))((("containers", see="Docker containers")))((("delivering payment", see="payment delivery")))((("DoS attacks", see="denial-of-service attacks")))((("encrypted message transport", see="Lightning encrypted transport protocol")))((("future issues", see="innovations in Lightning")))((("HTLCs", see="hash time-locked contracts")))((("invoices", see="Lightning invoices")))((("Lightning Network (generally)","Bitcoin compared to", see="Bitcoin–Lightning Network comparisons")))((("Lightning Network (generally)","invoices", see="Lightning invoices")))((("Lightning Network (generally)","network architecture", see="architecture, Lightning Network")))((("Lightning Network node", see="Lightning node entries")))((("Lightning payment requests", see="Lightning invoices")))((("LN node", see="Lightning node entries")))((("LND node project", see="Lightning Network Daemon node project")))((("message transport", see="Lightning encrypted transport protocol")))((("node", see="Lightning node entries")))((("payment channel","routing on network of", see="routing")))((("payment requests", see="Lightning invoices")))((("payment routing", see="routing")))((("privacy", see="breaches of privacy")))((("privacy", see="security and privacy")))((("private channels", see="unannounced channels")))((("TLV", see="Type-Length-Value")))((("wallet", see="Lightning wallet")))
